<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFskxRDT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFskxRDT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFskxRDT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFskxRDT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFskxRDT\App_KernelDevDebugContainer([
    'container.build_hash' => 'FskxRDT',
    'container.build_id' => 'a64eaf71',
    'container.build_time' => 1712113476,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFskxRDT');
